AllCops:
  Exclude:
    - "vendor/**/*"
    - db/schema.rb
  TargetRubyVersion: 2.6

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 100
  IgnoredPatterns: ['(\A|\s)#']

Style/Documentation:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - '**/*_spec.rb'

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'

Layout/TrailingBlankLines:
  Exclude:
    - 'config/initializers/wrap_parameters.rb'

Layout/TrailingWhitespace:
  Exclude:
    - 'config/initializers/backtrace_silencers.rb'

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'