development:
  adapter: postgresql
  encoding: unicode
  database: camisoteca_development
  pool: 5
  username: postgres
  host: db_1

test:
  adapter: postgresql
  encoding: unicode
  database: camisoteca_test
  pool: 5
  username: postgres
  host: db_1